spring.application.name=Web-Programming-Project

# Veritabanı bağlantı ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate ayarları
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Server port
server.port=8082

# Logging
logging.level.com.taskmanagement=DEBUG
logging.level.org.springframework.security=DEBUG

# Aspect için
spring.aop.proxy-target-class=true